# Generated by Django 5.2.8 on 2025-11-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('country_of_issue', models.CharField(blank=True, max_length=50, null=True)),
                ('user_role', models.CharField(choices=[('ADMIN', 'Administrator'), ('EMPLOYEE', 'Employee'), ('REPRESENTATIVE', 'NGO Representative'), ('VOLUNTEER', 'Volunteer')], default='VOLUNTEER', max_length=20)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('volunteer_id', models.IntegerField(blank=True, null=True)),
                ('representative_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
                'db_table': 'System_User',
                'managed': False,
            },
        ),
    ]
