-- SWITCH TO THE CONTAINER TO CREATE THE USER
ALTER SESSION SET CONTAINER = XEPDB1;

-- ========================================
-- TABLESPACE CREATION

CREATE TABLESPACE DATA_TABLES_REDROMERO
DATAFILE 'C:\APP\rodri\PRODUCT\21C\ORADATA\XE\data_tables_redRomero_01.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 50M
MAXSIZE 200M;

CREATE TABLESPACE INDEXES_REDROMERO
DATAFILE 'C:\APP\rodri\PRODUCT\21C\ORADATA\XE\indexes_redRomero_01.dbf'
SIZE 20M
AUTOEXTEND ON NEXT 20M
MAXSIZE 180M;

CREATE TEMPORARY TABLESPACE TEMP_REDROMERO
TEMPFILE 'C:\APP\rodri\PRODUCT\21C\ORADATA\XE\temp_redRomero_01.dbf'
SIZE 20M
AUTOEXTEND ON NEXT 10M
MAXSIZE 50M
EXTENT MANAGEMENT LOCAL
UNIFORM SIZE 2M;

CREATE TABLESPACE CONFIG_TABLES_REDROMERO
DATAFILE 'C:\APP\rodri\PRODUCT\21C\ORADATA\XE\config_tables_redRomero_01.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 5M
MAXSIZE 100M;

CREATE TABLESPACE HISTORY_TABLES_REDROMERO
DATAFILE 'C:\APP\rodri\PRODUCT\21C\ORADATA\XE\history_tables_redRomero_01.dbf'
SIZE 200M
AUTOEXTEND ON NEXT 10M
MAXSIZE 300M;

-- USER CREATION AND PERMISSION ASSIGNMENT


CREATE USER redRomero IDENTIFIED BY red123
DEFAULT TABLESPACE DATA_TABLES_REDROMERO
TEMPORARY TABLESPACE TEMP_REDROMERO
QUOTA UNLIMITED ON DATA_TABLES_REDROMERO
QUOTA UNLIMITED ON INDEXES_REDROMERO
QUOTA UNLIMITED ON CONFIG_TABLES_REDROMERO
QUOTA UNLIMITED ON HISTORY_TABLES_REDROMERO;

GRANT CONNECT, RESOURCE TO redRomero;
GRANT CREATE VIEW, CREATE SYNONYM, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE TO redRomero;
GRANT CREATE SESSION TO redRomero;

-- NEW CONNECTION Name Conexion_Romero
-- user redRomero
-- password red123
-- serviceName -> XEPDB1

